@baseURL = http://127.0.0.1:9000


###
# @name allAttractions

GET {{baseURL}}/address/

###
# @name CreateAttractions

POST {{baseURL}}/address/
Content-Type: application/json

{
    "linha1": "Ponte",
    "linha2": "Golden Gate",
    "cidade": "São francisco",
    "estado": "California",
    "pais": "EUA",
    "latitude": 2222,
    "longitude": 2222
}

###
# @name UpdateAttractions

PUT  {{baseURL}}/attractions/2/
Content-Type: application/json

{
    "name": "Bebedouro 2",
    "description": "Agua Quente",
    "time_func": "Seg-sexta",
    "minimum_age": 19
}

###
# @name Token

POST {{baseURL}}/api-token-auth/
Content-Type: application/json

{
    "username": "Api",
    "password": "Leonardo10!"
}