# Generated by Django 4.0.5 on 2022-06-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('evaluation', '0001_initial'),
        ('comments', '0001_initial'),
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.endereco')),
                ('attraction', models.ManyToManyField(to='attractions.atracao')),
                ('comment', models.ManyToManyField(to='comments.comentario')),
                ('evaluation', models.ManyToManyField(to='evaluation.avaliacao')),
            ],
        ),
    ]
