# Generated by Django 4.0.5 on 2022-06-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0002_pontoturistico_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.endereco'),
        ),
    ]
