# Generated by Django 4.0.5 on 2022-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0003_pontoturistico_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comment',
            field=models.ManyToManyField(to='comments.comentario'),
        ),
    ]
