# Generated by Django 4.0.5 on 2022-06-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_avaliacao_delete_avalicoes'),
        ('core', '0004_pontoturistico_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='assesment',
            field=models.ManyToManyField(to='assessments.avaliacao'),
        ),
    ]
